# Site settings
title: Owning the Sitecore Experience
email: adamsimsy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog focused on how Sitecore customers, developers & the community
  can Own the Sitecore Experience to deliver value for organisations & their users.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamsimsy.com" # the base hostname & protocol for your site
twitter_username: adamsimsy
github_username:  adamsimsy

# Build settings
markdown: kramdown
highlighter: rogue